### ISSUE TITLE
Data prevista implantação

### ISSUE THREAD

**Issue by henmerlin** [pjefika/pgd#4]
Obrigar preenchimento de motivo.
Exceção para criação inicial; 
Validar origem da Data Prevista (gerando atraso indevido) - Alterar fraseologia para: "Atrasado e No Prazo".

**Comment by FabioClem** [comment]
Já está obrigando o preenchimento do motivo ao cadastrar/modificar.
Corrigido validação da data de "hoje" para "No Prazo", data passada para atrasado data de hoje no prazo e data futura no prazo.
Modificado fraseologia ok.
